/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLoading: typeof import('./../components/common/app-loading.vue')['default']
    BaseBox: typeof import('./../components/base-box/index.vue')['default']
    BaseButton: typeof import('./../components/base-button/index.vue')['default']
    BaseDialog: typeof import('./../components/base-dialog/index.vue')['default']
    BaseIframe: typeof import('./../components/base-iframe/index.vue')['default']
    BaseLoading: typeof import('./../components/base-loading/index.vue')['default']
    BaseSkeleton: typeof import('./../components/base-skeleton/index.vue')['default']
    BetterScroll: typeof import('./../components/custom/better-scroll.vue')['default']
    ButtonIcon: typeof import('./../components/custom/button-icon.vue')['default']
    ChaseSpin: typeof import('./../components/base-loading/spin/chaseSpin.vue')['default']
    CubeSpin: typeof import('./../components/base-loading/spin/cubeSpin.vue')['default']
    DarkModeContainer: typeof import('./../components/common/dark-mode-container.vue')['default']
    DotSpin: typeof import('./../components/base-loading/spin/dotSpin.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ExceptionBase: typeof import('./../components/common/exception-base.vue')['default']
    FullScreen: typeof import('./../components/common/full-screen.vue')['default']
    LangSwitch: typeof import('./../components/common/lang-switch.vue')['default']
    LookForward: typeof import('./../components/custom/look-forward.vue')['default']
    MenuToggler: typeof import('./../components/common/menu-toggler.vue')['default']
    PinToggler: typeof import('./../components/common/pin-toggler.vue')['default']
    PlaneSpin: typeof import('./../components/base-loading/spin/planeSpin.vue')['default']
    PreloaderSpin: typeof import('./../components/base-loading/spin/preloaderSpin.vue')['default']
    PulseSpin: typeof import('./../components/base-loading/spin/pulseSpin.vue')['default']
    RectSpin: typeof import('./../components/base-loading/spin/rectSpin.vue')['default']
    ReloadButton: typeof import('./../components/common/reload-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
    SystemLogo: typeof import('./../components/common/system-logo.vue')['default']
    ThemeSchemaSwitch: typeof import('./../components/common/theme-schema-switch.vue')['default']
    WaveBg: typeof import('./../components/custom/wave-bg.vue')['default']
  }
}
